"""
PHANTOM GENESIS: Alpha Generator - The Meta-Generator
System: OmegaForge | Codename: Alpha

"The generator that generates generators"

This is the apex predator of the generator ecosystem - a recursive
self-bootstrapping system that can create new generators from
Generator DNA specifications.
"""

import json
import yaml
from typing import List, Dict, Any, Optional, Literal
from dataclasses import dataclass, field
from pathlib import Path
from .base import BaseGenerator, GeneratorContext, GeneratedFile
from .template_engine import TemplateEngine


@dataclass
class GeneratorOutputSpec:
    """Output file specification"""
    path: str
    template: str
    condition: Optional[str] = None
    per_technique: bool = False
    per_provider: bool = False
    description: Optional[str] = None


@dataclass
class GeneratorTemplateSpec:
    """Template specification"""
    id: str
    content: str
    description: Optional[str] = None
    partials: Optional[Dict[str, str]] = None


@dataclass
class GeneratorHelperSpec:
    """Custom helper specification"""
    name: str
    implementation: str  # Python code as string
    description: Optional[str] = None


@dataclass
class GeneratorHookSpec:
    """Hook specification"""
    type: Literal['beforeGenerate', 'afterGenerate', 'beforeWrite', 'afterWrite']
    implementation: str  # Python code as string


@dataclass
class GeneratorDNA:
    """Generator DNA - The specification for creating a new generator"""
    id: str  # kebab-case
    name: str
    system: str  # "XxxForge" pattern
    codename: str  # single word
    description: str
    version: str  # semver
    category: Literal['infrastructure', 'sdk', 'documentation', 'testing', 'monitoring', 'deployment']
    outputs: List[GeneratorOutputSpec]
    templates: List[GeneratorTemplateSpec]
    config_schema: Optional[Dict[str, Any]] = None
    dependencies: Optional[List[str]] = None
    helpers: Optional[List[GeneratorHelperSpec]] = None
    hooks: Optional[List[GeneratorHookSpec]] = None


class AlphaGenerator(BaseGenerator):
    """
    AlphaGenerator - The meta-generator that creates new generators
    
    This generator takes a Generator DNA specification and produces:
    1. A fully functional generator Python file
    2. Type definitions for the generator's configuration
    3. Test scaffolding for the generator
    4. Documentation for the generator
    """
    
    def __init__(self):
        super().__init__('alpha', 'Alpha Generator', 'The meta-generator that creates generators')
        self.generator_dna: List[GeneratorDNA] = []
        self.template_engine = TemplateEngine()
        self._load_base_templates()
    
    def _load_base_templates(self):
        """Load base templates for generator generation"""
        # Generator class template
        generator_template = '''"""
═══════════════════════════════════════════════════════════════════════════
PHANTOM GENESIS: {{ name }}
System: {{ system }} | Codename: {{ codename }}

{{ description }}

Auto-generated by Alpha Generator v{{ version }}
Generated: {{ timestamp }}
═══════════════════════════════════════════════════════════════════════════
"""

import asyncio
from typing import List, Dict, Any
from core.generators.base import BaseGenerator, GeneratorContext, GeneratedFile
from core.generators.template_engine import TemplateEngine


class {{ class_name }}(BaseGenerator):
    """{{ name }} - {{ description }}"""
    
    def __init__(self, config: Dict[str, Any] = None):
        super().__init__(
            '{{ id }}',
            '{{ name }}',
            '{{ description }}'
        )
        self.template_engine = TemplateEngine()
        self.config = config or {{ default_config }}
        self._register_templates()
        self._register_helpers()
    
    def _register_templates(self):
        """Register all templates"""
{% for template in templates %}
        self.template_engine.compile('{{ template.id }}', """{{ template.content }}""")
{% endfor %}
    
    def _register_helpers(self):
        """Register custom helpers"""
{% if helpers %}
{% for helper in helpers %}
        # {{ helper.description or helper.name }}
        def {{ helper.name }}(*args, **kwargs):
            {{ helper.implementation }}
        self.template_engine.register_helper('{{ helper.name }}', {{ helper.name }})
{% endfor %}
{% else %}
        # No custom helpers defined
{% endif %}
    
    async def generate(self, context: GeneratorContext) -> List[GeneratedFile]:
        """Main generation entry point"""
        files: List[GeneratedFile] = []
        
        for provider in context.providers:
{% for output in outputs %}
{% if output.per_technique %}
            # {{ output.description or output.path }}
            for technique in provider.get('techniques', []):
                path = self.resolve_path('{{ output.path }}', provider=provider, technique=technique)
                content = self.template_engine.render('{{ output.template }}', {
                    'provider': provider,
                    'technique': technique,
                    'namespace': context.namespace,
                    'config': self.config,
                })
                files.append(GeneratedFile(
                    path=path,
                    content=content,
                    description='{{ output.description or "" }}'
                ))
{% else %}
            # {{ output.description or output.path }}
            path = self.resolve_path('{{ output.path }}', provider=provider)
            content = self.template_engine.render('{{ output.template }}', {
                'provider': provider,
                'namespace': context.namespace,
                'config': self.config,
            })
            files.append(GeneratedFile(
                path=path,
                content=content,
                description='{{ output.description or "" }}'
            ))
{% endif %}
{% endfor %}
        
        self.generated_files = files
        return files
'''
        
        self.template_engine.compile('generator_class', generator_template)
    
    def load_generator_dna(self, dna: GeneratorDNA | List[GeneratorDNA]):
        """Load Generator DNA specifications"""
        if isinstance(dna, list):
            self.generator_dna.extend(dna)
        else:
            self.generator_dna.append(dna)
    
    def load_dna_from_file(self, filepath: str):
        """Load Generator DNA from YAML or JSON file"""
        path = Path(filepath)
        if not path.exists():
            raise FileNotFoundError(f"DNA file not found: {filepath}")
        
        # Use async file I/O if available
        if AIOFILES_AVAILABLE:
            async with aiofiles.open(path, 'r', encoding='utf-8') as f:
                content = await f.read()
        else:
            with open(path, 'r', encoding='utf-8') as f:
                content = f.read()
            if path.suffix in ['.yaml', '.yml']:
                data = yaml.safe_load(f)
            else:
                data = json.load(f)
        
        # Convert dict to GeneratorDNA
        dna = self._dict_to_dna(data)
        self.load_generator_dna(dna)
    
    def _dict_to_dna(self, data: Dict[str, Any]) -> GeneratorDNA:
        """Convert dictionary to GeneratorDNA"""
        return GeneratorDNA(
            id=data['id'],
            name=data['name'],
            system=data['system'],
            codename=data['codename'],
            description=data['description'],
            version=data['version'],
            category=data['category'],
            outputs=[GeneratorOutputSpec(**o) for o in data['outputs']],
            templates=[GeneratorTemplateSpec(**t) for t in data['templates']],
            config_schema=data.get('configSchema'),
            dependencies=data.get('dependencies'),
            helpers=[GeneratorHelperSpec(**h) for h in data['helpers']] if data.get('helpers') else None,
            hooks=[GeneratorHookSpec(**h) for h in data['hooks']] if data.get('hooks') else None,
        )
    
    async def generate(self, context: GeneratorContext) -> List[GeneratedFile]:
        """Generate new generators from DNA"""
        files: List[GeneratedFile] = []
        
        for dna in self.generator_dna:
            # Generate main generator file
            files.append(self._generate_generator_file(dna, context))
            
            # Generate types file
            files.append(self._generate_types_file(dna))
            
            # Generate test file
            files.append(self._generate_test_file(dna))
            
            # Generate README
            files.append(self._generate_readme(dna))
        
        self.generated_files = files
        return files
    
    def _generate_generator_file(self, dna: GeneratorDNA, context: GeneratorContext) -> GeneratedFile:
        """Generate the main generator Python file"""
        class_name = self.to_pascal_case(dna.id) + 'Generator'
        instance_name = self.to_camel_case(dna.id) + 'Generator'
        
        # Prepare default config
        default_config = self._generate_default_config(dna)
        
        # Render template
        content = self.template_engine.render('generator_class', {
            'id': dna.id,
            'name': dna.name,
            'system': dna.system,
            'codename': dna.codename,
            'description': dna.description,
            'version': context.version,
            'timestamp': context.timestamp,
            'class_name': class_name,
            'instance_name': instance_name,
            'templates': dna.templates,
            'outputs': dna.outputs,
            'helpers': dna.helpers or [],
            'default_config': default_config,
        })
        
        return GeneratedFile(
            path=f"core/generators/{dna.id}_generator.py",
            content=content,
            description=f"{dna.name} - {dna.description}",
        )
    
    def _generate_default_config(self, dna: GeneratorDNA) -> str:
        """Generate default configuration dict"""
        if not dna.config_schema:
            return "{'output_dir': './generated', 'namespace': 'ouroboros'}"
        
        defaults = []
        for key, schema in dna.config_schema.get('properties', {}).items():
            default_val = schema.get('default', self._get_default_for_type(schema.get('type', 'string')))
            defaults.append(f"'{key}': {repr(default_val)}")
        
        return '{' + ', '.join(defaults) + '}'
    
    def _get_default_for_type(self, type_name: str) -> Any:
        """Get default value for a type"""
        defaults = {
            'string': '',
            'number': 0,
            'integer': 0,
            'boolean': False,
            'array': [],
            'object': {},
        }
        return defaults.get(type_name, None)
    
    def _generate_types_file(self, dna: GeneratorDNA) -> GeneratedFile:
        """Generate type definitions file"""
        class_name = self.to_pascal_case(dna.id)
        
        template_ids = [t.id for t in dna.templates]
        
        content = f'''"""
Type definitions for {dna.name}
System: {dna.system} | Codename: {dna.codename}

Auto-generated by Alpha Generator
"""

from typing import List, Dict, Any
from core.generators.base import GeneratedFile


class {class_name}Output:
    """Output from {dna.name} generator"""
    files: List[GeneratedFile]
    metadata: Dict[str, Any]


class {class_name}Metadata:
    """Metadata for {dna.name} generation"""
    generator: str = "{dna.id}"
    version: str = "{dna.version}"
    timestamp: str
    provider: str
    technique_count: int


{class_name}Template = Literal[{', '.join(f"'{t}'" for t in template_ids)}]
'''
        
        return GeneratedFile(
            path=f"core/generators/{dna.id}_types.py",
            content=content,
            description=f"Type definitions for {dna.name}",
        )
    
    def _generate_test_file(self, dna: GeneratorDNA) -> GeneratedFile:
        """Generate test file"""
        class_name = self.to_pascal_case(dna.id) + 'Generator'
        instance_name = self.to_camel_case(dna.id) + 'Generator'
        
        content = f'''"""
Tests for {dna.name}
System: {dna.system} | Codename: {dna.codename}

Auto-generated by Alpha Generator
"""

import pytest
from core.generators.base import GeneratorContext
from core.generators.{dna.id}_generator import {class_name}


# Mock provider for testing
MOCK_PROVIDER = {{
    'id': 'test-provider',
    'name': 'Test Provider',
    'version': '1.0.0',
    'description': 'A test provider',
    'category': 'general',
    'techniques': [
        {{
            'id': 'TEST-GEN-01',
            'name': 'Test Technique',
            'description': 'A test technique',
            'category': 'general',
        }},
    ],
}}


MOCK_CONTEXT = GeneratorContext(
    providers=[MOCK_PROVIDER],
    namespace='test',
    version='1.0.0',
    environment='test',
    output_dir='./test-output',
)


@pytest.mark.asyncio
class Test{class_name}:
    """Tests for {class_name}"""
    
    async def test_initialization(self):
        """Test generator initialization"""
        generator = {class_name}()
        assert generator.generator_id == '{dna.id}'
        assert generator.name == '{dna.name}'
    
    async def test_generation(self):
        """Test file generation"""
        generator = {class_name}()
        files = await generator.generate(MOCK_CONTEXT)
        assert len(files) > 0
    
    async def test_generated_content(self):
        """Test generated content validity"""
        generator = {class_name}()
        files = await generator.generate(MOCK_CONTEXT)
        for file in files:
            assert file.path
            assert file.content
'''
        
        return GeneratedFile(
            path=f"tests/unit/test_{dna.id}_generator.py",
            content=content,
            description=f"Tests for {dna.name}",
        )
    
    def _generate_readme(self, dna: GeneratorDNA) -> GeneratedFile:
        """Generate README documentation"""
        outputs_list = '\n'.join(f"- `{o.path}` - {o.description or 'No description'}" for o in dna.outputs)
        templates_list = '\n'.join(f"### {t.id}\n\n{t.description or 'No description'}\n" for t in dna.templates)
        deps_list = '\n'.join(f"- `{d}`" for d in (dna.dependencies or []))
        
        content = f'''# {dna.name}

**System:** {dna.system} | **Codename:** {dna.codename}

{dna.description}

## Overview

| Property | Value |
|----------|-------|
| ID | `{dna.id}` |
| Version | `{dna.version}` |
| Category | `{dna.category}` |

## Generated Files

{outputs_list}

## Templates

{templates_list}

## Usage

```python
from core.generators.{dna.id}_generator import {self.to_pascal_case(dna.id)}Generator

generator = {self.to_pascal_case(dna.id)}Generator()
files = await generator.generate(context)
```

## Configuration

```python
generator = {self.to_pascal_case(dna.id)}Generator({{
    # Custom configuration options
}})
```

{f"## Dependencies\n\nThis generator depends on:\n\n{deps_list}\n" if dna.dependencies else ""}

---

*Auto-generated by Alpha Generator*
'''
        
        return GeneratedFile(
            path=f"docs/generators/{dna.id}.md",
            content=content,
            description=f"Documentation for {dna.name}",
        )

